FROM ghcr.io/zitadel/zitadel:latest
COPY testbed/clever-cloud/zitadel/zitadel-config.yaml /
CMD start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --config zitadel-config.yaml --tlsMode external